version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: fitty_db
    environment:
      POSTGRES_USER: fitty_user
      POSTGRES_PASSWORD: fitty_password
      POSTGRES_DB: fitty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: